version: '3.8'

services:
  linear-issues-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linear-issues-mcp
    stdin_open: true  # Required for stdin communication with MCP
    tty: true         # Required for proper terminal handling
    environment:
      - LINEAR_API_KEY=${LINEAR_API_KEY}
      - SERVER_NAME=${SERVER_NAME:-linear-issues-mcp}
      - SERVER_VERSION=${SERVER_VERSION:-1.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LINEAR_MCP_TOOLS=${LINEAR_MCP_TOOLS:-issues,comments,labels}  # Tool groups to enable
      - LINEAR_MCP_VERBOSE=${LINEAR_MCP_VERBOSE:-false}               # Enable verbose logging
    volumes:
      - ./:/app    # For development, mount source code
      - /app/node_modules  # Don't overwrite node_modules
    restart: unless-stopped
    # You can override the command with CLI arguments, e.g.:
    # command: ["node", "dist/index.js", "--issues-only"] 